### ISSUE TITLE
Gaussian Mixture Model example bug

### ISSUE THREAD

**Issue by pkubik** [brendanhasz/probflow#4]
Related to the example:
https://probflow.readthedocs.io/en/latest/example_gmm.html

The model is defined as follows:
```
class GaussianMixtureModel(pf.Model):
    def __init__(self, k, d, *args):
        super().__init__(*args)
        self.mu = pf.Parameter([k, d])
        self.sigma = pf.ScaleParameter([k, d])
        self.theta = pf.DirichletParameter(k)

    def __call__(self):
        dists = tfd.MultivariateNormalDiag(self.mu(), self.sigma())
        return pf.Mixture(dists, probs=self.theta())
```

And then evaluated as:
```
Np = 100  # number of grid points
xx = np.linspace(-6, 6, Np)
Xp, Yp = np.meshgrid(xx, xx)
Pp = np.column_stack([Xp.ravel(), Yp.ravel()])
probs = model.prob(Pp.astype('float32'))
```

This produces following error, because there is no X -> Y mapping in this example. This is pure generative model:

```
TypeError: __call__() takes 1 positional argument but 2 were given
```

`model.prob` calls the above implemenation of `__call__` which doesn't accept any `x`.

It can be easily fixed by passing the values as `y`:
```
probs = model.prob(x=None, y=Pp.astype('float32'))
```

I'm not sure whether it's documentation or implementation error. It would seem more natural to just provide the X-value if the Y is not present in the model.

**Comment by brendanhasz** [comment]
Hi!

Thanks for pointing out the issue!  Looks like there was a bug with the older version on PyPi (so, the docs are correct and it's an implementation error which had been fixed since, but I hadn't updated the packaged version).  Released the newest version on PyPi, which should work with that example. You should be able to install the updated version with either

```bash
pip install --upgrade probflow
```

or, directly from the source on github:

```bash
pip install git+https://github.com/brendanhasz/probflow.git
```

Thanks again and let me know if that solves the problem.

Cheers,

Brendan

**Comment by pkubik** [comment]
Thanks, it works now. I'll use the git version from now on.
