### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by jejjohnson** [brendanhasz/probflow#5]
Hello!

First of all, I really like this package you've created! It's a really nice stepping stone into the world of Bayesian NN without the need for a lot of boilerplate code.

But, I was wondering if you had a priority list potential contributions? Also perhaps a schematic of what type of things should be added or what things are out of the scope of this package?

Thanks,
Emmanuel

**Comment by jejjohnson** [comment]
Nevermind, I found your list in the [backlog section](https://probflow.readthedocs.io/en/latest/todo.html)!

Closing.

**Comment by jejjohnson** [comment]
I think it would find it useful for potential devs to at least know what's out of the scope. 

Thanks again!

**Comment by brendanhasz** [comment]
Added an out-of-scope section to the backlog page, thanks for the idea!  

Unfortunately, I included Gaussian Processes in that list (and it appears you've done a lot of work with GPs - so, sorry! haha) since I found it a bit hard to figure out how to fit nonparametric models into the ProbFlow framework (e.g., the `probflow.model.predict` interface would have to change, and all the methods which depend on it, since you'd need both the x and y training data as well as the x test data).  For more info on that see https://github.com/brendanhasz/probflow/issues/7
